#!/bin/bash

# Get the list of staged files
STAGED_FILES=$(git diff --cached --name-only)

# Check if the target file is staged
for TARGET_FILE in $STAGED_FILES; do
  # Replace occurrences of ${datasource} with ${datasource}
  sed -i 's/\${datasource}/\${datasource}/g' "$TARGET_FILE"
  sed -i 's/\${datasource}/\${datasource}/g' "$TARGET_FILE"

  git add "$TARGET_FILE"

done
