{
 "title": "Clamav",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_namespace_created,cluster)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_status_initialized_time{cluster=\"$cluster\", namespace=\"clamav\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General infos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clamav version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamav_version{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clamav DB last update",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamav_db_timestamp_seconds{cluster=\"$cluster\"} * 1e3",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clamav replicas up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum (clamav_up{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clamav DB version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamav_db_version{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Live threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum by (pod) (clamav_pool_live_threads{cluster=\"$cluster\", pod=~\"$pod\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum by (pod) (clamav_pool_max_threads{cluster=\"$cluster\", pod=~\"$pod\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Idle threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum by (pod) (clamav_pool_idle_threads{cluster=\"$cluster\", pod=~\"$pod\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Idle timeout threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "sum by (pod) (clamav_pool_idle_timeout_threads{cluster=\"$cluster\", pod=~\"$pod\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queue wait time (min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum by (pod) (clamav_pool_queue_min_wait_sec{cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Queue wait time (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum by (pod) (clamav_pool_queue_max_wait_sec{cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Queue length",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum (clamav_pool_queue_length{cluster=\"$cluster\", pod=~\"$pod\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Queue avg wait time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (pod) (clamav_pool_queue_avg_wait_sec{cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Exporter infos",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total HTTP code returned",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (code) (promhttp_metric_handler_requests_total{cluster=\"$cluster\", container=\"clamav-exporter\", pod=~\"$pod\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP code returned",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 10 },
     "targets": [
      {
       "expr": "sum by (code) (rate(promhttp_metric_handler_requests_total{cluster=\"$cluster\", container=\"clamav-exporter\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network received & transmitted (in bytes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (rate(process_network_receive_bytes_total{cluster=\"$cluster\", container=\"clamav-exporter\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Received bytes"
      },
      {
       "expr": "sum (-rate(process_network_transmit_bytes_total{cluster=\"$cluster\", container=\"clamav-exporter\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Transimitted bytes"
      }
     ]
    },
    {
     "title": "Exporter requests in flight",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "sum (promhttp_metric_handler_requests_in_flight{cluster=\"$cluster\", pod=~\"$pod\", container=\"clamav-exporter\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}