{
 "title": "Cluster requests and pods failure",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "pod_phase",
    "label": "Pods' phase",
    "query": {
     "query": "label_values(kube_pod_status_phase{cluster=\"$cluster\"}, phase)"
    }
   },
   {
    "name": "pod_reason",
    "label": "Pods' reason",
    "query": {
     "query": "label_values(kube_pod_status_reason{cluster=\"$cluster\"}, reason)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU requests by namespace",
     "type": "timeseries",
     "gridPos": { "h": 23, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_node_status_capacity{cluster=\"$cluster\", namespace=~\"$namespace\", resource=\"cpu\", node!~\".*master.*\"})",
       "legendFormat": "Cluster capacity"
      },
      {
       "expr": "namespace_cpu:kube_pod_container_resource_requests:sum{cluster=\"$cluster\", namespace=~\"$namespace\", }",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "$pod_phase CPU requests by namespace",
     "type": "timeseries",
     "gridPos": { "h": 23, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (namespace) (\n  namespace_cpu:priority_class:requests:sum{cluster=\"$cluster\", namespace=~\"$namespace\", phase=\"$pod_phase\"}\n)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "MEM requests by namespace",
     "type": "timeseries",
     "gridPos": { "h": 23, "w": 24, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kube_node_status_capacity{cluster=\"$cluster\", namespace=~\"$namespace\", resource=\"memory\", node!~\".*master.*\"})",
       "legendFormat": "Cluster capacity"
      },
      {
       "expr": "namespace_memory:kube_pod_container_resource_requests:sum{cluster=\"$cluster\", namespace=~\"$namespace\"}",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU phases",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU phases",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (phase) (\n  namespace_cpu:priority_class:requests:sum{cluster=\"$cluster\", namespace=~\"$namespace\"}\n)",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "CPU ${pod_phase} by namespace",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 229 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (namespace) (\n  namespace_cpu:priority_class:requests:sum{cluster=\"$cluster\", namespace=~\"$namespace\", phase=\"$pod_phase\"}\n)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "CPU ${pod_phase} by priority-class",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 242 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (priority_class) (\n    namespace_cpu:priority_class:requests:sum{cluster=\"$cluster\", namespace=~\"$namespace\", phase=\"$pod_phase\"}\n)\n",
       "legendFormat": "{{priority_class}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods' phases",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods' phases",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 159 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (phase) (kube_pod_status_phase{cluster=\"$cluster\", namespace=~\"$namespace\"} > 0)",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "${pod_phase} by namespace",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 230 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (namespace) (kube_pod_status_phase{cluster=\"$cluster\", namespace=~\"$namespace\", phase=\"$pod_phase\"} > 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${pod_phase} by priority-class",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 243 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (priority_class) (\n    (kube_pod_status_phase{cluster=\"$cluster\", namespace=~\"$namespace\", phase=\"$pod_phase\"} > 0)\n    * on(namespace,pod)\n    group_left(priority_class) kube_pod_info{cluster=\"$cluster\", namespace=~\"$namespace\"}\n)",
       "legendFormat": "{{priority_class}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods' reasons",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods' reasons",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (reason) (kube_pod_status_reason{cluster=\"$cluster\", namespace=~\"$namespace\"})",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "${pod_reason} by namespace",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (namespace) (kube_pod_status_reason{cluster=\"$cluster\", namespace=~\"$namespace\", reason=\"$pod_reason\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${pod_reason} by Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (node) (kube_pod_status_reason{cluster=\"$cluster\", namespace=~\"$namespace\", reason=\"$pod_reason\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "${pod_reason} by priority-class",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (priority_class) (\n    kube_pod_status_reason{cluster=\"$cluster\", namespace=~\"$namespace\", reason=\"$pod_reason\"}\n    * on(namespace,pod)\n    group_left(priority_class) kube_pod_info{cluster=\"$cluster\", namespace=~\"$namespace\"}\n)",
       "legendFormat": "{{priority_class}}"
      }
     ]
    }
   ]
  }
 ]
}