{
 "title": "Docker Hub Rate Limits",
 "description": "Docker Hub Rate Limits",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Pull Requests",
   "type": "gauge",
   "description": "Image Pull Requests (limit 100/6hours)",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dockerhub_limit_max_requests_total{instance=~'.*'}) - sum(dockerhub_limit_remaining_requests_total{instance=~'.*'})",
     "legendFormat": "Used requests"
    },
    {
     "expr": "sum(dockerhub_limit_remaining_requests_total{instance=~'.*'})",
     "legendFormat": "Remaining requests"
    },
    {
     "expr": "sum(dockerhub_limit_max_requests_total{instance=~'.*'})",
     "legendFormat": "Max requests"
    }
   ]
  },
  {
   "title": "Max Image Pull Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(dockerhub_limit_max_requests_total{instance=~'.*'})"
    }
   ]
  },
  {
   "title": "Used Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dockerhub_limit_max_requests_total{instance=~'.*'} - on(instance) dockerhub_limit_remaining_requests_total{instance=~'.*'}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Remaining Requests",
   "type": "timeseries",
   "description": "Remaining Requests",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dockerhub_limit_remaining_requests_total",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}