{
 "title": "ElasticSearch Detailed",
 "description": "ElasticSearch cluster stats",
 "tags": [
  "elasticsearch",
  "App"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Сluster",
    "query": {
     "query": "label_values(elasticsearch_indices_docs,cluster)"
    }
   },
   {
    "name": "name",
    "label": "Node name",
    "query": {
     "query": "label_values(elasticsearch_indices_docs{cluster=\"$cluster\", name!=\"\"},name)"
    }
   },
   {
    "name": "instance",
    "label": "Source of metrics",
    "query": {
     "query": "label_values(elasticsearch_indices_docs{cluster=\"$cluster\", name!=\"\"},instance)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "KPI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_status{cluster=\"$cluster\",color=\"red\"}==1 or (elasticsearch_cluster_health_status{cluster=\"$cluster\",color=\"green\"}==1)+4 or (elasticsearch_cluster_health_status{cluster=\"$cluster\",color=\"yellow\"}==1)+22"
    }
   ]
  },
  {
   "title": "Tripped for breakers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(elasticsearch_breakers_tripped{cluster=\"$cluster\",name=~\"$name\"}>0)"
    }
   ]
  },
  {
   "title": "CPU usage Avg.",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (elasticsearch_process_cpu_percent{cluster=\"$cluster\",name=~\"$name\"} ) / count (elasticsearch_process_cpu_percent{cluster=\"$cluster\",name=~\"$name\"} )"
    }
   ]
  },
  {
   "title": "JVM memory used Avg.",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (elasticsearch_jvm_memory_used_bytes{cluster=\"$cluster\",name=~\"$name\"}) / sum (elasticsearch_jvm_memory_max_bytes{cluster=\"$cluster\",name=~\"$name\"}) * 100"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "description": "Number of nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_nodes{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Data nodes",
   "type": "stat",
   "description": "Number of data nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_data_nodes{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Pending tasks",
   "type": "stat",
   "description": "Cluster level changes which have not yet been executed",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_pending_tasks{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Open file descriptors per cluster",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (elasticsearch_process_open_files_count{cluster=\"$cluster\",name=~\"$name\"})"
    }
   ]
  },
  { "title": "Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Active primary shards",
   "type": "stat",
   "description": "The number of primary shards in your cluster. This is an aggregate total across all indices.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 5 },
   "repeat": "shard_type",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_primary_shards{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Active shards",
   "type": "stat",
   "description": "Aggregate total of all shards across all indices, which includes replica shards",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_shards{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Initializing shards",
   "type": "stat",
   "description": "Count of shards that are being freshly created",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_initializing_shards{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Relocating shards",
   "type": "stat",
   "description": "The number of shards that are currently moving from one node to another node.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_relocating_shards{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Delayed shards",
   "type": "stat",
   "description": "Shards delayed to reduce reallocation overhead",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_delayed_unassigned_shards{cluster=\"$cluster\"} "
    }
   ]
  },
  {
   "title": "Unassigned shards",
   "type": "stat",
   "description": "The number of shards that exist in the cluster state, but cannot be found in the cluster itself",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_unassigned_shards{cluster=\"$cluster\"} "
    }
   ]
  },
  { "title": "JVM Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "GC count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_jvm_gc_collection_seconds_count{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}} - {{gc}}"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_jvm_gc_collection_seconds_sum{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}} - {{gc}}"
    }
   ]
  },
  { "title": "Translog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Total translog operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_translog_operations{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total translog size in bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_translog_size_in_bytes{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Breakers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tripped for breakers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "elasticsearch_breakers_tripped{cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}}: {{breaker}}"
      }
     ]
    },
    {
     "title": "Estimated size in bytes of breaker",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "elasticsearch_breakers_estimated_size_bytes{cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}}: {{breaker}}"
      },
      {
       "expr": "elasticsearch_breakers_limit_size_bytes{cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}}: limit for {{breaker}}"
      }
     ]
    }
   ]
  },
  { "title": "CPU and Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Load average",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "elasticsearch_os_load1{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "load1: {{name}}"
    },
    {
     "expr": "elasticsearch_os_load5{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "load5: {{name}}"
    },
    {
     "expr": "elasticsearch_os_load15{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "load15: {{name}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "elasticsearch_process_cpu_percent{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "JVM memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "elasticsearch_jvm_memory_used_bytes{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}} used: {{area}}"
    },
    {
     "expr": "elasticsearch_jvm_memory_max_bytes{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}} max: {{area}}"
    },
    {
     "expr": "elasticsearch_jvm_memory_pool_peak_used_bytes{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}} peak used pool: {{pool}}"
    }
   ]
  },
  {
   "title": "JVM memory committed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "elasticsearch_jvm_memory_committed_bytes{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}} committed: {{area}}"
    },
    {
     "expr": "elasticsearch_jvm_memory_max_bytes{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}} max: {{area}}"
    }
   ]
  },
  {
   "title": "Disk and Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 74 },
     "targets": [
      {
       "expr": "1-(elasticsearch_filesystem_data_available_bytes{cluster=\"$cluster\",name=~\"$name\"}/elasticsearch_filesystem_data_size_bytes{cluster=\"$cluster\",name=~\"$name\"})",
       "legendFormat": "{{name}}: {{path}}"
      }
     ]
    },
    {
     "title": "Network usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 74 },
     "targets": [
      {
       "expr": "rate(elasticsearch_transport_tx_size_bytes_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: sent "
      },
      {
       "expr": "-rate(elasticsearch_transport_rx_size_bytes_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: received"
      }
     ]
    }
   ]
  },
  {
   "title": "Documents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Documents count on node",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "elasticsearch_indices_docs{cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Documents indexed rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 75 },
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_indexing_index_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Documents deleted rate",
     "type": "timeseries",
     "description": "Count of deleted documents on this node",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 155 },
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_docs_deleted{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Documents merged rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 155 },
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_merges_docs_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Documents merged bytes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 155 },
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_merges_total_size_bytes_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  { "title": "Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Query time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_search_query_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$interval]) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Indexing time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Merging time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_merges_total_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Throttle time for index store",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_store_throttle_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Total Operations stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Total Operations  rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: indexing"
    },
    {
     "expr": "rate(elasticsearch_indices_search_query_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: query"
    },
    {
     "expr": "rate(elasticsearch_indices_search_fetch_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: fetch"
    },
    {
     "expr": "rate(elasticsearch_indices_merges_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: merges"
    },
    {
     "expr": "rate(elasticsearch_indices_refresh_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: refresh"
    },
    {
     "expr": "rate(elasticsearch_indices_flush_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: flush"
    },
    {
     "expr": "rate(elasticsearch_indices_get_exists_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: get_exists"
    },
    {
     "expr": "rate(elasticsearch_indices_get_missing_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: get_missing"
    },
    {
     "expr": "rate(elasticsearch_indices_get_tota{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: get"
    },
    {
     "expr": "rate(elasticsearch_indices_indexing_delete_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: indexing_delete"
    }
   ]
  },
  {
   "title": "Total Operations time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: indexing"
    },
    {
     "expr": "rate(elasticsearch_indices_search_query_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: query"
    },
    {
     "expr": "rate(elasticsearch_indices_search_fetch_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: fetch"
    },
    {
     "expr": "rate(elasticsearch_indices_merges_total_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: merges"
    },
    {
     "expr": "rate(elasticsearch_indices_refresh_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: refresh"
    },
    {
     "expr": "rate(elasticsearch_indices_flush_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: flush"
    },
    {
     "expr": "rate(elasticsearch_indices_get_exists_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: get_exists"
    },
    {
     "expr": "rate(elasticsearch_indices_get_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: get_time"
    },
    {
     "expr": "rate(elasticsearch_indices_get_missing_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: get_missing"
    },
    {
     "expr": "rate(elasticsearch_indices_indexing_delete_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: indexing_delete"
    },
    {
     "expr": "rate(elasticsearch_indices_get_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: get"
    }
   ]
  },
  { "title": "Thread Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Thread Pool operations rejected",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 6, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "rate(elasticsearch_thread_pool_rejected_count{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: {{ type }}"
    }
   ]
  },
  {
   "title": "Thread Pool operations queued",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 6, "x": 6, "y": 97 },
   "targets": [
    {
     "expr": "elasticsearch_thread_pool_active_count{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}: {{ type }}"
    }
   ]
  },
  {
   "title": "Thread Pool threads active",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 6, "x": 12, "y": 97 },
   "targets": [
    {
     "expr": "elasticsearch_thread_pool_active_count{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}: {{ type }}"
    }
   ]
  },
  {
   "title": "Thread Pool operations completed",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 6, "x": 18, "y": 97 },
   "targets": [
    {
     "expr": "rate(elasticsearch_thread_pool_completed_count{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: {{ type }}"
    }
   ]
  },
  { "title": "Caches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 } },
  {
   "title": "Field data memory size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 117 },
   "targets": [
    {
     "expr": "elasticsearch_indices_fielddata_memory_size_bytes{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Field data evictions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 117 },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_fielddata_evictions{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Query cache size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 127 },
   "targets": [
    {
     "expr": "elasticsearch_indices_query_cache_memory_size_bytes{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Query cache evictions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 127 },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_query_cache_evictions{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Evictions from filter cache",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 127 },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_filter_cache_evictions{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Segments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count of index segments",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 238 },
     "targets": [
      {
       "expr": "elasticsearch_indices_segments_count{cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Current memory size of segments in bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 245 },
     "targets": [
      {
       "expr": "elasticsearch_indices_segments_memory_bytes{cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: Count of documents and Total size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 138 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count of documents with only primary shards",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 246 },
     "targets": [
      {
       "expr": "elasticsearch_indices_docs_primary{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Total size of stored index data in bytes with only primary shards on all nodes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 253 },
     "targets": [
      {
       "expr": "elasticsearch_indices_store_size_bytes_primary{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Total size of stored index data in bytes with all shards on all nodes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 260 },
     "targets": [
      {
       "expr": "elasticsearch_indices_store_size_bytes_total{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: Index writer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 },
   "collapsed": true,
   "panels": [
    {
     "title": "Index writer with only primary shards on all nodes in bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 261 },
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_index_writer_memory_bytes_primary{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Index writer with all shards on all nodes in bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 268 },
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_index_writer_memory_bytes_total{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: Segments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 },
   "collapsed": true,
   "panels": [
    {
     "title": "Segments with only primary shards on all nodes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 269 },
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_count_primary{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Segments with all shards on all nodes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 276 },
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_count_total{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Size of segments with only primary shards on all nodes in bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 283 },
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_memory_bytes_primary{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Size of segments with all shards on all nodes in bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 290 },
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_memory_bytes_total{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: Doc values",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 },
   "collapsed": true,
   "panels": [
    {
     "title": "Doc values with only primary shards on all nodes in bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 291 },
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_doc_values_memory_bytes_primary{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Doc values with all shards on all nodes in bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 298 },
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_doc_values_memory_bytes_total{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: Fields",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 142 },
   "collapsed": true,
   "panels": [
    {
     "title": "Size of fields with only primary shards on all nodes in bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 299 },
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_fields_memory_bytes_primary{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Size of fields with all shards on all nodes in bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 306 },
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_fields_memory_bytes_total{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: Fixed bit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 143 },
   "collapsed": true,
   "panels": [
    {
     "title": "Size of fixed bit with only primary shards on all nodes in bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 307 },
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_fixed_bit_set_memory_bytes_primary{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Size of fixed bit with all shards on all nodes in bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 314 },
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_fixed_bit_set_memory_bytes_total{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: Norms",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 },
   "collapsed": true,
   "panels": [
    {
     "title": "Size of norms with only primary shards on all nodes in bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 315 },
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_norms_memory_bytes_primary{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Size of norms with all shards on all nodes in bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 322 },
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_norms_memory_bytes_total{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: Points",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 },
   "collapsed": true,
   "panels": [
    {
     "title": "Size of points with only primary shards on all nodes in bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 323 },
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_points_memory_bytes_primary{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Size of points with all shards on all nodes in bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 330 },
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_points_memory_bytes_total{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: Terms",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 146 },
   "collapsed": true,
   "panels": [
    {
     "title": "Size of terms with only primary shards on all nodes in bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 331 },
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_terms_memory_primary{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Number of terms with all shards on all nodes in bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 338 },
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_terms_memory_total{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: Version map",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 },
   "collapsed": true,
   "panels": [
    {
     "title": "Size of version map with only primary shards on all nodes in bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 339 },
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_version_map_memory_bytes_primary{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Size of version map with all shards on all nodes in bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 346 },
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_version_map_memory_bytes_total{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  }
 ]
}