{
 "title": "Container exit by reasons",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "reason",
    "label": "Reason",
    "query": {
     "query": "label_values(kube_pod_container_status_last_terminated_reason{cluster=\"$cluster\"}, reason)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod_name",
    "label": "Pod's name",
    "query": {
     "query": "label_values(kube_pod_container_status_last_terminated_reason{cluster=\"$cluster\", namespace=~\"$namespace\", reason=\"$reason\"}, pod)"
    }
   },
   {
    "name": "container_name",
    "label": "Container's name",
    "query": {
     "query": "label_values(kube_pod_container_status_last_terminated_reason{cluster=\"$cluster\", namespace=~\"$namespace\", reason=\"$reason\", pod=\"$pod_name\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$reason pod by (namespace, pod, container) in the namespace(s)",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (namespace, pod, container) (\n    max_over_time(kube_pod_container_status_last_terminated_reason{cluster=\"$cluster\", namespace=~\"[[namespace]].*\", reason=\"$reason\"}[$__range])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU/MEM graphs for pod-container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory for $pod_name / $container_name",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=~\"[[namespace]].*\", pod=~\"[[pod_name]].*\", container=~\"[[container_name]].*\", container!=\"\", container!=\"POD\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=~\"[[namespace]].*\", pod=~\"[[pod_name]].*\", container=~\"[[container_name]].*\", container!=\"\", container!=\"POD\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=~\"[[namespace]].*\", pod=~\"[[pod_name]].*\", container=~\"[[container_name]].*\", container!=\"\", container!=\"POD\"})",
       "legendFormat": "Real"
      }
     ]
    },
    {
     "title": "CPU $pod_name / $container_name",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=~\"[[namespace]].*\", pod=~\"[[pod_name]].*\", container=~\"[[container_name]].*\", container!=\"\", container!=\"POD\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=~\"[[namespace]].*\", pod=~\"[[pod_name]].*\", container=~\"[[container_name]].*\", container!=\"\", container!=\"POD\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster.*\", namespace=~\"[[namespace]].*\", pod=~\"[[pod_name]].*\", container=~\"[[container_name]].*\", image!=\"\", pod!=\"\", container!=\"POD\", container!=\"\"}[5m]))",
       "legendFormat": "Real"
      }
     ]
    }
   ]
  },
  {
   "title": "Global reasons",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod count by reason",
     "type": "timeseries",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (reason) (kube_pod_container_status_last_terminated_reason{cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$reason pod by namespace",
     "type": "timeseries",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (namespace) (kube_pod_container_status_last_terminated_reason{cluster=\"$cluster\", reason=\"$reason\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}