{
 "title": "Fluentd dashboard (Prometheus exporter)",
 "description": "A quick dashboard for displaying Fluentd metrics.",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Output status emit records",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(fluentd_output_status_emit_records[30m])"
    }
   ]
  },
  {
   "title": "buffer queue length",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(fluentd_status_buffer_queue_length[10m])"
    }
   ]
  },
  {
   "title": "buffer total queued size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg_over_time(fluentd_status_buffer_total_bytes[10m])"
    }
   ]
  },
  {
   "title": "retry count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(fluentd_status_retry_count[$__rate_interval])"
    }
   ]
  }
 ]
}