{
 "title": "GitLab - Pages",
 "description": "Dashboard for Gitlab sidekiq\n",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\"},cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(gitlab_build_info{cluster=~\"$cluster\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (cluster, namespace, container) (\n  gitlab_pages_http_in_flight_requests{cluster=\"$cluster\", namespace=\"$namespace\"}\n)",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (cluster, namespace, container) (\n  rate(gitlab_pages_http_request_duration_seconds_sum{cluster=\"$cluster\", namespace=\"$namespace\", method=\"get\", code=\"200\"}[5m])\n)\n/\nclamp_min(\n  sum by (cluster, namespace, container) (\n    rate(gitlab_pages_http_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", method=\"get\", code=\"200\"}[5m])\n  ),\n  1\n)\n",
     "legendFormat": "Seconds"
    }
   ]
  },
  {
   "title": "Average Response Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (cluster, namespace, container) (\n  rate(gitlab_pages_http_response_size_bytes_sum{cluster=\"$cluster\", namespace=\"$namespace\", method=\"get\", code=\"200\"}[5m])\n)\n/\nclamp_min(\n  sum by (cluster, namespace, container) (\n    rate(gitlab_pages_http_response_size_bytes_count{cluster=\"$cluster\", namespace=\"$namespace\", method=\"get\", code=\"200\"}[5m])\n  ),\n  1\n)\n",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Average Time to Write Header",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (cluster, namespace, container) (\n  rate(gitlab_pages_http_time_to_write_header_seconds_sum{cluster=\"$cluster\", namespace=\"$namespace\", method=\"get\", code=\"200\"}[5m])\n)\n/\nclamp_min(\n  sum by (cluster, namespace, container) (\n    rate(gitlab_pages_http_time_to_write_header_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", method=\"get\", code=\"200\"}[5m])\n  ),\n  1\n)\n",
     "legendFormat": "Seconds"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (cluster, namespace, container) (\n  rate(gitlab_pages_domains_source_cache_hit{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])\n)\n/\nclamp_min(\n  sum by (cluster, namespace, container) (\n    rate(gitlab_pages_domains_source_cache_hit{cluster=\"$cluster\", namespace=\"$namespace\"}[5m]) +\n    rate(gitlab_pages_domains_source_cache_miss{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])\n  ),\n  1\n)\n",
     "legendFormat": "Hits"
    }
   ]
  },
  {
   "title": "API Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (cluster, namespace, container) (\n  rate(gitlab_pages_domains_source_failures_total{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])\n)\n",
     "legendFormat": "Failures"
    }
   ]
  },
  {
   "title": "Concurrency Gauges",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (cluster, namespace, container) (\n  gitlab_pages_limit_listener_concurrent_conns{cluster=\"$cluster\", namespace=\"$namespace\"}\n)\n",
     "legendFormat": "Concurrent"
    },
    {
     "expr": "sum by (cluster, namespace, container) (\n  gitlab_pages_limit_listener_max_conns{cluster=\"$cluster\", namespace=\"$namespace\"}\n)\n",
     "legendFormat": "Max"
    },
    {
     "expr": "sum by (cluster, namespace, container) (\n  gitlab_pages_limit_listener_waiting_conns{cluster=\"$cluster\", namespace=\"$namespace\"}\n)\n",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "Recovered Panics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by (cluster, namespace, container) (\n  increase(gitlab_pages_panic_recovered_count{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])\n)\n",
     "legendFormat": "Count"
    }
   ]
  }
 ]
}