{
 "title": "GitLab - Shell",
 "description": "Dashboard for Gitlab sidekiq\n",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\"},cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(gitlab_build_info{cluster=~\"$cluster\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (cluster, namespace, container) (gitlab_shell_http_in_flight_requests{cluster=\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "SSH Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (cluster, namespace, container) (gitlab_shell_sshd_in_flight_connections{cluster=\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "SSH Session Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (cluster, namespace, container) (rate(gitlab_shell_sshd_session_duration_seconds_sum{cluster=\"$cluster\", namespace=\"$namespace\"}[5m]))\n/\nclamp_min(\nsum by (cluster, namespace, container) (rate(gitlab_shell_sshd_session_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])),\n1\n)",
     "legendFormat": "Seconds"
    }
   ]
  },
  {
   "title": "SSH Session Establish Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (cluster, namespace, container) (rate(gitlab_shell_sshd_session_established_duration_seconds_sum{cluster=\"$cluster\", namespace=\"$namespace\"}[5m]))\n/\nclamp_min(\nsum by (cluster, namespace, container) (rate(gitlab_shell_sshd_session_established_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])),\n  1\n)",
     "legendFormat": "Seconds"
    }
   ]
  },
  {
   "title": "SSH Session Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (cluster, namespace, container) (rate(gitlab_sli:shell_sshd_sessions:errors_total{cluster=\"$cluster\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "SSH Sessions Established",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (cluster, namespace, container) (gitlab_sli:shell_sshd_sessions:total{cluster=\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "Sessions"
    }
   ]
  },
  {
   "title": "Concurrent Session Limit Hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (cluster, namespace, container) (increase(gitlab_shell_sshd_concurrent_limited_sessions_total{cluster=\"$cluster\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Hits"
    }
   ]
  }
 ]
}