{
 "title": "GitLab - Sidekiq",
 "description": "Dashboard for Gitlab sidekiq\n",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\"},cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(gitlab_build_info{cluster=~\"$cluster\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Background Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sidekiq_jobs_processed_total{cluster=\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "Processed"
    },
    {
     "expr": "max(sidekiq_jobs_failed_total{cluster=\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "max(sidekiq_jobs_enqueued_size{cluster=\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "Enqueued"
    },
    {
     "expr": "max(sidekiq_jobs_scheduled_size{cluster=\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "Scheduled"
    },
    {
     "expr": "max(sidekiq_jobs_retry_size{cluster=\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "Retry"
    },
    {
     "expr": "max(sidekiq_jobs_dead_size{cluster=\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "Dead"
    },
    {
     "expr": "max(sidekiq_processes_size{cluster=\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "Processes"
    }
   ]
  },
  {
   "title": "Sidekiq Rss",
   "type": "stat",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pid) (sidekiq_mem_total_bytes{cluster=\"$cluster\", namespace=\"$namespace\", instance=~\"$instance\", job=~\"gitlab-sidekiq\"})",
     "legendFormat": "{{pid}}"
    }
   ]
  },
  {
   "title": "Jobs  Time consumption",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum (rate(sidekiq_jobs_db_seconds_sum{cluster=\"$cluster\", namespace=\"$namespace\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "db"
    },
    {
     "expr": "sum (rate(sidekiq_jobs_cpu_seconds_sum{cluster=\"$cluster\", namespace=\"$namespace\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "cpu"
    },
    {
     "expr": "sum (rate(sidekiq_redis_requests_duration_seconds_sum{cluster=\"$cluster\", namespace=\"$namespace\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "redis"
    },
    {
     "expr": "sum (rate(sidekiq_jobs_queue_duration_seconds_sum{cluster=\"$cluster\", namespace=\"$namespace\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "queue"
    },
    {
     "expr": "sum (rate(sidekiq_jobs_gitaly_seconds_sum{cluster=\"$cluster\", namespace=\"$namespace\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "gitaly"
    },
    {
     "expr": "sum (rate(sidekiq_jobs_completion_seconds_sum{cluster=\"$cluster\", namespace=\"$namespace\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "completion"
    }
   ]
  },
  {
   "title": "Queue Size Top 10",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, avg_over_time(sidekiq_queue_size{cluster=\"$cluster\", namespace=\"$namespace\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Load Balancing Strategy",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (load_balancing_strategy) (rate(sidekiq_load_balancing_count{cluster=\"$cluster\", namespace=\"$namespace\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{load_balancing_strategy}}"
    }
   ]
  }
 ]
}