{
 "title": "Keycloak Metrics Dashboard, Kubernetes flavor",
 "description": "Dashboard of Keycloak metrics exported with Keycloak Metrics SPIhttps://github.com/aerogear/keycloak-metrics-spi",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(keycloak_response_created{namespace=\"$namespace\"},service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Memory HEAP",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{namespace=\"$namespace\", service=\"$service\", area=\"heap\"})*100 / sum(jvm_memory_bytes_max{namespace=\"$namespace\", service=\"$service\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Current Memory nonHEAP",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{namespace=\"$namespace\", service=\"$service\", area=\"nonheap\"})*100/sum(jvm_memory_bytes_max{namespace=\"$namespace\", service=\"$service\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_max{namespace=\"$namespace\", service=\"$service\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{namespace=\"$namespace\", service=\"$service\"})",
     "legendFormat": "Comitted"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{namespace=\"$namespace\", service=\"$service\", })",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Logins Per REALM for past 24h all instances",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(realm) (increase(keycloak_logins_total{namespace=\"$namespace\", service=\"$service\"}[24h]))",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "Registrations Per REALM for past 24h all instances",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(realm) (increase(keycloak_registrations_total{namespace=\"$namespace\", service=\"$service\"}[24h]))",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "Logins Per CLIENT for past 24h all instances",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(client_id) (increase(keycloak_logins_total{namespace=\"$namespace\", service=\"$service\"}[24h]))",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Registrations Per CLIENT for past 24h",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(client_id) (increase(keycloak_registrations_total{namespace=\"$namespace\", service=\"$service\"}[24h]))",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "4xx and 5xx Responses all instances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(code) (increase(keycloak_response_errors_total{namespace=\"$namespace\", service=\"$service\"}[30m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Logins per REALM all instances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(realm) (increase(keycloak_logins_total{namespace=\"$namespace\", service=\"$service\"}[30m]))",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "Login Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (error, realm) (increase(keycloak_failed_login_attempts_total{namespace=\"$namespace\", service=\"$service\"}[30m]))",
     "legendFormat": "{{$realm }} {{error}}"
    }
   ]
  },
  {
   "title": "Logins per CLIENT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (client_id)(increase(keycloak_logins_total{namespace=\"$namespace\", service=\"$service\"}[30m]))",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Registration Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (realm) (increase(keycloak_registrations_errors_total{namespace=\"$namespace\", service=\"$service\"}[30m]))",
     "legendFormat": "Sum by {{realm}}"
    },
    { "legendFormat": "{{error}}" }
   ]
  },
  {
   "title": "Registrations per REALM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(realm) (increase(keycloak_registrations_total{namespace=\"$namespace\", service=\"$service\"}[30m]))",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "Login Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (error) (increase(keycloak_failed_login_attempts_total{namespace=\"$namespace\", service=\"$service\"}[30m]))",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Registrations per CLIENT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (client_id)(increase(keycloak_registrations_total{namespace=\"$namespace\", service=\"$service\"}[30m]))",
     "legendFormat": "{{client_id}}"
    },
    { "legendFormat": "Sum by {{realm}}" }
   ]
  },
  {
   "title": "Registration Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "legendFormat": "{{error}}" }
   ]
  },
  {
   "title": "Request duration method = \"GET\" Heatmap all instances",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum by(le) (increase(keycloak_request_duration_bucket{method=\"GET\", namespace=\"$namespace\", service=\"$service\"}[30m]))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Percentage of requests \"GET\"  method  was served in 100ms or below all instances",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(keycloak_request_duration_bucket{method=\"GET\", le=\"100.0\", namespace=\"$namespace\", service=\"$service\"}[30m])) * 100) / sum(rate(keycloak_request_duration_count{method=\"GET\", namespace=\"$namespace\", service=\"$service\"}[30m]))"
    }
   ]
  },
  {
   "title": "Request duration method = \"POST\" Heatmap all instances",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sum by(le) (increase(keycloak_request_duration_bucket{method=\"POST\", namespace=\"$namespace\", service=\"$service\"}[30m]))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Percentage of requests \"POST\"  method  was served in 100ms or below all instances",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(keycloak_request_duration_bucket{method=\"POST\", le=\"100.0\", namespace=\"$namespace\", service=\"$service\"}[30m])) * 100) / sum(rate(keycloak_request_duration_count{method=\"POST\", namespace=\"$namespace\", service=\"$service\"}[30m]))"
    }
   ]
  },
  {
   "title": "Request duration method = \"HEAD\" Heatmap all instances",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "sum by(le) (increase(keycloak_request_duration_bucket{method=\"HEAD\", namespace=\"$namespace\", service=\"$service\"}[30m]))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Percentage of requests \"HEAD\"  method  was served in 100ms or below all instances",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(keycloak_request_duration_bucket{method=\"HEAD\", le=\"100.0\", namespace=\"$namespace\", service=\"$service\"}[30m])) * 100) / sum(rate(keycloak_request_duration_count{method=\"HEAD\", namespace=\"$namespace\", service=\"$service\"}[30m]))"
    }
   ]
  },
  {
   "title": "Request duration method = \"PUT\" Heatmap all instances",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "targets": [
    { "legendFormat": "{{ le }}" }
   ]
  },
  {
   "title": "Percentage of requests \"PUT\"  method  was served in 100ms or below all instances",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(keycloak_request_duration_bucket{method=\"PUT\", le=\"100.0\", namespace=\"$namespace\", service=\"$service\"}[30m])) * 100) / sum(rate(keycloak_request_duration_count{method=\"PUT\", namespace=\"$namespace\", service=\"$service\"}[30m]))"
    }
   ]
  }
 ]
}