{
 "title": "koherence",
 "description": "koherence",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_namespace_created,cluster)"
    }
   },
   { "name": "node_name", "label": "Node(s) name", "query": ".*" }
  ]
 },
 "panels": [
  { "title": "koherence count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "inkoherence count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "koherence_diff_count{cluster=\"$cluster\", node_name=~\"$node_name\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "koherence count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "koherence_merged_count{cluster=\"$cluster\", node_name=~\"$node_name\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  { "title": "mutli-attach", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "count multi attach by node_name",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (node_name) (koherence_multiattach_active{cluster=\"$cluster\", node_name=~\"$node_name\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "multi-attach",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "count by (volume_id, server_id, attachment_id, node_name) (koherence_multiattach_active{cluster=\"$cluster\", node_name=~\"$node_name\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}