{
 "title": "Node: overloaded nodes",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_namespace_created, cluster)"
    }
   },
   { "name": "node_name", "label": "Node(s) name", "query": ".*" },
   { "name": "query_min_threshold", "label": "Query Minimum Threshold", "query": "1" }
  ]
 },
 "panels": [
  {
   "title": "CPU load / amount of cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (instance) (node_load15{instance=~\"$node_name\", cluster=~\".*$cluster\"}) / count(count(node_cpu_seconds_total{instance=~\"$node_name\", cluster=~\".*$cluster\"}) by (cpu, instance)) by (instance) > $query_min_threshold",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node related, can be cpu intensive",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "(container, namespace) exceeding by 2 cpu their request",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "(\nsum by (container, namespace) (rate(container_cpu_usage_seconds_total{cluster=~\".*$cluster\", node=~\"$node_name\", container!=\"\", container!=\"POD\"}[15m]))\n-\nsum by (container, namespace) (avg_over_time(kube_pod_container_resource_requests{resource=\"cpu\", cluster=~\".*$cluster\", node=~\"$node_name\"}[15m]))\n) > 2",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU system / softirq / iowait too high",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (mode, instance, cluster) (\n    (rate(node_cpu_seconds_total{instance=~\"$node_name\", cluster=~\".*$cluster\", mode=~\"system|iowait|softirq\"}[30m]))\n) > 0.2",
     "legendFormat": "{{mode}}: {{instance}} / {{cluster}}"
    }
   ]
  },
  {
   "title": "Node Pods & containers amount",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods number",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum(\n  kube_pod_status_phase{cluster=~\"$cluster\", phase=~\"Running\"}\n  * on (uid) group_right\n  kube_pod_info{cluster=~\"$cluster\", node=~\"$node_name\"}\n) by (node)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Containers number",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "sum by (node) (\n    kube_pod_container_info{cluster=~\"$cluster\"}\n    * on (cluster, namespace, pod) group_left (node)\n    (kube_pod_status_phase{cluster=~\"$cluster\", phase=~\"Running\"}\n    * on (uid, cluster, namespace, pod) group_right\n    kube_pod_info{cluster=~\"$cluster\", node=~\"$node_name\"})\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}