{
 "title": "Vector",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_namespace_created,cluster)"
    }
   },
   {
    "name": "node",
    "query": {}
   },
   {
    "name": "pod",
    "query": {}
   },
   {
    "name": "log_level",
    "query": {}
   },
   {
    "name": "component_kind",
    "query": {
     "query": "label_values(vector_component_received_event_bytes_total{cluster=~\"$cluster\"},component_kind)"
    }
   },
   {
    "name": "component_type",
    "query": {
     "query": "label_values(vector_component_received_event_bytes_total{cluster=~\"$cluster\", component_kind=~\"$component_kind\"},component_type)"
    }
   },
   {
    "name": "component_id",
    "query": {
     "query": "label_values(vector_component_received_event_bytes_total{cluster=~\"$cluster\", component_kind=~\"$component_kind\", component_type=~\"$component_type\"},component_id)"
    }
   },
   { "name": "search" }
  ]
 },
 "panels": [
  { "title": "Source - kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kubernetes - files added",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(vector_files_added_total{cluster=~\"$cluster\", component_kind=\"source\", component_type=\"kubernetes_logs\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes - files unwatched",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(vector_files_unwatched_total{cluster=~\"$cluster\", component_kind=\"source\", component_type=\"kubernetes_logs\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes - opened files ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (pod) (vector_open_files{cluster=~\"$cluster\", component_kind=\"source\", component_type=\"kubernetes_logs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes - checksum errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(vector_checksum_errors_total{cluster=~\"$cluster\", component_kind=\"source\", component_type=\"kubernetes_logs\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Components", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Received event by component",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (component_id) (rate(vector_component_received_events_total{cluster=~\"$cluster\", component_kind=~\"$component_kind\", component_type=~\"$component_type\", component_id=~\"$component_id\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent event by component",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (component_id) (rate(vector_component_sent_events_total{cluster=~\"$cluster\", component_kind=~\"$component_kind\", component_type=~\"$component_type\", component_id=~\"$component_id\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors by component",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by (component_id) (rate(vector_component_errors_total{cluster=~\"$cluster\", component_kind=~\"$component_kind\", component_type=~\"$component_type\", component_id=~\"$component_id\", pod=~\"$pod\"}[$__rate_interval])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discarded events by component",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum by (component_id) (rate(vector_component_discarded_events_total{cluster=~\"$cluster\", component_kind=~\"$component_kind\", component_type=~\"$component_type\", component_id=~\"$component_id\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received bytes by component",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (component_id) (rate(vector_component_received_bytes_total{cluster=~\"$cluster\", component_kind=~\"$component_kind\", component_type=~\"$component_type\", component_id=~\"$component_id\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent bytes by component",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (component_id) (rate(vector_component_sent_bytes_total{cluster=~\"$cluster\", component_kind=~\"$component_kind\", component_type=~\"$component_type\", component_id=~\"$component_id\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "{source=\"vector\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\", log_level=~\"$log_level\", component_kind=~\"$component_kind\", component_type=~\"$component_type\", component_id=~\"$component_id\"} |~ `$search` | json"
      }
     ]
    }
   ]
  }
 ]
}