{
 "title": "Postgres Autovacuum",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(pg_up, namespace)" } },
   {
    "name": "job",
    "query": {
     "query": "label_values(pg_up{namespace=\"$namespace\"}, job)"
    }
   },
   {
    "name": "datname",
    "query": {
     "query": "label_values(pg_stat_database_stats_reset{job=\"$job\", namespace=\"$namespace\"}, datname)\t"
    }
   },
   {
    "name": "relname",
    "query": {
     "query": "label_values(pg_stat_user_tables_idx_scan{job=\"$job\", namespace=\"$namespace\", datname=\"$datname\"}, relname)\t"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Disk space used by database",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (datname) (pg_database_size_bytes{namespace=\"$namespace\",job=\"$job\",datname=\"$datname\"})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Table size (no Toast, no Indexes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (relname) (pg_stat_user_tables_relation_size{namespace=\"$namespace\",job=\"$job\",datname=\"$datname\",relname=~\"$relname\"})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Table size / Live Tuples",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (relname) (pg_stat_user_tables_relation_size{namespace=\"$namespace\",job=\"$job\",datname=\"$datname\",relname=~\"$relname\"}) / sum by (relname) (pg_stat_user_tables_n_live_tup{namespace=\"$namespace\",job=\"$job\",datname=\"$datname\",relname=~\"$relname\"})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Corresponding TOAST",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_live_tup{namespace=\"$namespace\",job=\"$job\",datname=\"$datname\"}"
    }
   ]
  },
  { "title": "TUPLES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Approximate Live tuples",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (relname) (pg_stat_user_tables_n_live_tup{namespace=\"$namespace\",job=\"$job\",datname=\"$datname\",relname=~\"$relname\"})",
     "legendFormat": "{{relname}}"
    },
    {
     "expr": "sum by (relname) (pg_stat_user_tables_autovacuum_count{namespace=\"$namespace\",job=\"$job\",datname=\"$datname\",relname=~\"$relname\"})",
     "legendFormat": "Vaccum_count {{relname}} "
    }
   ]
  },
  {
   "title": "Approximate Dead tuples",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (relname) (pg_stat_user_tables_n_dead_tup{namespace=\"$namespace\",job=\"$job\",relname=~\"$relname\"})",
     "legendFormat": "{{relname}}"
    },
    {
     "expr": "sum by (relname) (pg_stat_user_tables_autovacuum_count{namespace=\"$namespace\",job=\"$job\",datname=\"$datname\",relname=~\"$relname\"})",
     "legendFormat": "Vacuum_count {{relname}}"
    }
   ]
  },
  {
   "title": "Inserted tuples irate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (relname) (rate(pg_stat_user_tables_n_tup_ins{namespace=\"$namespace\",job=\"$job\",datname=~\"$datname\",relname=~\"$relname\"}[$__rate_interval]))",
     "legendFormat": "{{relname}}"
    },
    {
     "expr": "sum by (relname) (pg_stat_user_tables_autovacuum_count{namespace=\"$namespace\",job=\"$job\",datname=\"$datname\",relname=~\"$relname\"})",
     "legendFormat": "Vacuum_count {{relname}}"
    }
   ]
  },
  {
   "title": "Deleted tuples irate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (relname) (rate(pg_stat_user_tables_n_tup_del{namespace=\"$namespace\",job=\"$job\",datname=\"$datname\",relname=~\"$relname\"}[$__rate_interval]))",
     "legendFormat": "{{relname}}"
    },
    {
     "expr": "sum by (relname) (pg_stat_user_tables_autovacuum_count{namespace=\"$namespace\",job=\"$job\",datname=\"$datname\",relname=~\"$relname\"})",
     "legendFormat": "Vacuum_count {{relname}}"
    }
   ]
  },
  {
   "title": "Updated tuples irate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (relname) (rate(pg_stat_user_tables_n_tup_upd{namespace=\"$namespace\",job=\"$job\",datname=\"$datname\",relname=~\"$relname\"}[$__rate_interval]))",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  { "title": "AUTOVACUUM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Autovacuum increase last hour",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (relname) (increase(pg_stat_user_tables_autovacuum_count{namespace=\"$namespace\",job=\"$job\",datname=\"$datname\",relname=~\"$relname\"}[1h]))",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Last Autovacuum Finish time",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - pg_stat_user_tables_last_autovacuum{namespace=\"$namespace\",job=\"$job\",datname=\"$datname\",relname=~\"$relname\"}",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Heap blocks + tuples",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 17, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (relname) (pg_stat_progress_vacuum_heap_blks_scanned{namespace=\"$namespace\",job=\"$job\",datname=\"$datname\",relname=~\"$relname\"})",
     "legendFormat": "Scanned blocks {{relname}} "
    },
    {
     "expr": "sum by (relname) (pg_stat_progress_vacuum_heap_blks_total{namespace=\"$namespace\",job=\"$job\",datname=\"$datname\",relname=~\"$relname\"})",
     "legendFormat": "Total blocks {{relname}} "
    },
    {
     "expr": "sum by (relname) (pg_stat_progress_vacuum_heap_blks_vacuumed{namespace=\"$namespace\",job=\"$job\",datname=\"$datname\",relname=~\"$relname\"})",
     "legendFormat": "Vacuumed blocks {{relname}} "
    },
    {
     "expr": "sum by (relname) (pg_stat_progress_vacuum_phase{namespace=\"$namespace\",job=\"$job\",datname=\"$datname\",relname=~\"$relname\"})",
     "legendFormat": "Vacuum Phase {{relname}} "
    },
    {
     "expr": "sum by (relname) (pg_stat_progress_vacuum_num_dead_tuples{namespace=\"$namespace\",job=\"$job\",datname=\"$datname\",relname=~\"$relname\"})",
     "legendFormat": "Collected dead tuples {{relname}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 13, "w": 7, "x": 17, "y": 35 },
   "options": {
    "content": "# Vacuum Phases\n\n- 0: initializing\n- 1: scanning heap\n- 2: vacuuming indexes\n- 3: vacuuming heap\n- 4: cleaning up indexes\n- 5: truncating heap\n- 6: performing final cleanup\n\nhttps://www.postgresql.org/docs/12/progress-reporting.html for more details\n"
   }
  },
  {
   "title": "Autovacuum backend wait event type",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (backend_wait_event_type) (count_over_time(pg_stat_progress_vacuum_pid{namespace=\"$namespace\",job=\"$job\",datname=\"$datname\",relname=~\"$relname\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Autovacuum backend wait event name",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (backend_wait_event) (count_over_time(pg_stat_progress_vacuum_pid{namespace=\"$namespace\",job=\"$job\",datname=\"$datname\",relname=~\"$relname\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Autovacuum backend wait event type count over last 24h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by (backend_wait_event_type) (count_over_time(pg_stat_progress_vacuum_pid{namespace=\"$namespace\",job=\"$job\",datname=\"$datname\",relname=~\"$relname\"}[24h]))"
    }
   ]
  },
  {
   "title": "Autovacuum backend wait event type count over last 24h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum by (backend_wait_event) (count_over_time(pg_stat_progress_vacuum_pid{namespace=\"$namespace\",job=\"$job\",datname=\"$datname\",relname=~\"$relname\"}[24h]))"
    }
   ]
  },
  {
   "title": "WIP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "running transactions longer than 30s count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_long_xact_count{namespace=\"$namespace\",job=\"$job\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "running transactions longer than 1m count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_one_minute_long_xact_count{namespace=\"$namespace\",job=\"$job\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "running transactions longer than 3m count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_three_minutes_long_xact_count{namespace=\"$namespace\",job=\"$job\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "running transactions longer than 10m count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_ten_minutes_long_xact_count{namespace=\"$namespace\",job=\"$job\"}",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  }
 ]
}