{
 "title": "Postgres Backup/Restore",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(wal_g_last_backup_start_time_seconds, namespace)"
    }
   },
   {
    "name": "postgresql_cluster",
    "label": "Postgresql",
    "query": {
     "query": "label_values(pg_stat_archiver_archived_count{namespace=~\"$namespace\"},job)"
    }
   },
   {
    "name": "walg",
    "label": "Wal-G Selector",
    "query": {
     "query": "label_values(wal_g_last_backup_start_time_seconds{namespace=~\"$namespace\"},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Last Successful  Backup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backup Start Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wal_g_last_backup_start_time_seconds{namespace=\"$namespace\", job=~\"$walg\"} * 1000"
    }
   ]
  },
  {
   "title": "Backup Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wal_g_last_backup_finish_time_seconds{namespace=\"$namespace\", job=~\"$walg\"}  - wal_g_last_backup_start_time_seconds{namespace=\"$namespace\", job=~\"$walg\"}"
    }
   ]
  },
  {
   "title": "Backup End Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wal_g_last_backup_finish_time_seconds{namespace=\"$namespace\", job=~\"$walg\"} * 1000"
    }
   ]
  },
  {
   "title": "Backup Uncompressed Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wal_g_last_backup_uncompressed_size_bytes{namespace=\"$namespace\", job=~\"$walg\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compression Ratio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wal_g_last_backup_uncompressed_size_bytes{namespace=\"$namespace\", job=~\"$walg\"} / wal_g_last_backup_compressed_size_bytes{namespace=\"$namespace\", job=~\"$walg\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backup Compressed Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wal_g_last_backup_compressed_size_bytes{namespace=\"$namespace\", job=~\"$walg\"}"
    }
   ]
  },
  { "title": "Wal Archiving", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Nb of successfully archived WAL during the last 30 minutes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (increase(pg_stat_archiver_archived_count{namespace=\"$namespace\", job=~\"$postgresql_cluster\"}[30m]))"
    }
   ]
  },
  {
   "title": "Time since last successful WAL archive (Estimated Recovery Point Objective)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_archiver_last_archive_age{namespace=\"$namespace\", job=~\"$postgresql_cluster\"}"
    }
   ]
  },
  {
   "title": "Number of failed WAL archiving attempts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_archiver_failed_count{namespace=\"$namespace\", job=~\"$postgresql_cluster\"}"
    }
   ]
  },
  { "title": "Restore Test in Progress (WIP)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Restore Test Start Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wal_g_restore_test_in_progress_seconds{namespace=\"$namespace\", job=~\"$postgresql_cluster\"} * 1000"
    }
   ]
  },
  { "title": "Last Successful Restore Test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Restore Test Start Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wal_g_last_restore_test_start_time_seconds{namespace=\"$namespace\", job=~\"$postgresql_cluster\"} * 1000"
    }
   ]
  },
  {
   "title": "Test state Until",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wal_g_last_restore_test_last_insert_seconds{namespace=\"$namespace\", job=~\"$postgresql_cluster\"} * 1000"
    }
   ]
  },
  {
   "title": "Restore Test Duration (Estimated Recovery Time Objective)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wal_g_last_restore_test_finish_time_seconds{namespace=\"$namespace\", job=~\"$postgresql_cluster\"} - wal_g_last_restore_test_start_time_seconds{namespace=\"$namespace\", job=~\"$postgresql_cluster\"}"
    }
   ]
  },
  {
   "title": "Restore Test End Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wal_g_last_restore_test_finish_time_seconds{namespace=\"$namespace\", job=~\"$postgresql_cluster\"} * 1000"
    }
   ]
  }
 ]
}