{
 "title": "RabbitMQ Monitoring",
 "description": "Rabbitmq stats using RabbitMQ Exporter (https://github.com/kbudde/rabbitmq_exporter)",
 "tags": [
  "rabbitmq",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(rabbitmq_running,namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(rabbitmq_running{namespace=\"$namespace\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RabbitMQ Nodes Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rabbitmq_running{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Nodes Up",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rabbitmq_running{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Connections, channels and consumers",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_connectionsTotal{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "connections"
    },
    {
     "expr": "rabbitmq_channelsTotal{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "channels"
    },
    {
     "expr": "rabbitmq_consumersTotal{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "consumers"
    }
   ]
  },
  {
   "title": "Messages per Queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Messages status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (queue)(rabbitmq_queue_messages_ready{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "{{queue}}:ready"
    },
    {
     "expr": "sum by (queue)(rabbitmq_queue_messages_published_total{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "{{queue}}:published"
    },
    {
     "expr": "sum by (queue)(rabbitmq_queue_messages_delivered_total{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "{{queue}}:delivered"
    },
    {
     "expr": "sum by (queue)(rabbitmq_queue_messages_unacknowledged{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "{{queue}}:unack"
    }
   ]
  },
  {
   "title": "Free disk space",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rabbitmq_node_disk_free{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "{{job}}:free"
    },
    {
     "expr": "rabbitmq_node_disk_free_limit{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "{{job}}:limit"
    }
   ]
  },
  {
   "title": "Used memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rabbitmq_node_mem_used{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "{{job}}:used"
    },
    {
     "expr": "rabbitmq_node_mem_limit{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "{{job}}:limit"
    }
   ]
  }
 ]
}