{
 "title": "Redis Dashboard for Prometheus Redis Exporter 1.x",
 "description": "Redis Dashboard for Prometheus Redis Exporter 1.x",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(redis_up, service)"
    }
   },
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Commands per second",
   "type": "graph",
   "description": "Average taken across instances",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(redis_commands_total{service=~\"$service\"} [$__rate_interval])) by (cmd)",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Command latency per second",
   "type": "graph",
   "description": "Average taken across instances",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(irate(redis_commands_duration_seconds_total{service=~\"$service\"}[$__rate_interval])) by (cmd)\n  /\navg(irate(redis_commands_total{service=~\"$service\"}[$__rate_interval])) by (cmd)\n",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Hit ratio per instance",
   "type": "graph",
   "description": "Hit rate shows the percentage of key space lookups that hit a key.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(redis_keyspace_hits_total{service=~\"$service\"}[$__rate_interval]) / (irate(redis_keyspace_misses_total{service=~\"$service\"}[$__rate_interval]) + irate(redis_keyspace_hits_total{service=~\"$service\"}[$__rate_interval]))) by (instance)",
     "legendFormat": "{{instance}}"
    },
    { "expr": "1", "legendFormat": "Target hit ratio for cache" }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "description": "Total taken across instances",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(redis_memory_used_bytes{service=~\"$service\"})",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "sum(redis_memory_max_bytes{service=~\"$service\"})",
     "legendFormat": "Configured max memory"
    },
    {
     "expr": "sum(redis_memory_used_rss_bytes{service=~\"$service\"})",
     "legendFormat": "Used RSS memory"
    }
   ]
  },
  {
   "title": "Memory fragmentation ratio per instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_memory_fragmentation_ratio{service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Key evictions per second per instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_evicted_keys_total{service=~\"$service\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Basic activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Connected/Blocked Clients",
   "type": "graph",
   "description": "Sum taken across instances",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_connected_clients{service=~\"$service\"})",
     "legendFormat": "Connected"
    },
    {
     "expr": "sum(redis_blocked_clients{service=~\"$service\"})",
     "legendFormat": "Blocked"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "description": "Sum taken across instances",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{service=~\"$service\"}) by (db)",
     "legendFormat": "{{ db }}"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "description": "Sum taken across instances",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{service=~\"$service\"}) - sum (redis_db_keys_expiring{service=~\"$service\"})",
     "legendFormat": "Not expiring"
    },
    {
     "expr": "sum(redis_db_keys_expiring{service=~\"$service\"})",
     "legendFormat": "Expiring"
    }
   ]
  },
  {
   "title": "Connected slaves by instance",
   "type": "graph",
   "description": "This metric will only be non-zero if the instance is a master",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_connected_slaves{service=~\"$service\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time since last master connection",
   "type": "graph",
   "description": "This metric is only exported if the instance is a slave.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "redis_master_last_io_seconds_ago{service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}