{
 "title": "RabbitMQ queues details",
 "tags": [ "rabbitmq-prometheus" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\"},cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(rabbitmq_identity_info{cluster=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "rabbitmq_cluster",
    "label": "RabbitMQ Cluster",
    "query": {
     "query": "label_values(rabbitmq_identity_info{cluster=~\"$cluster\", namespace=~\"$namespace\"},rabbitmq_cluster)"
    }
   },
   {
    "name": "rabbitmq_vhost",
    "label": "Vhost",
    "query": {
     "query": "query_result(rabbitmq_queue_messages  * on(instance, job) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{cluster=~\"$cluster\", namespace=~\"$namespace\", rabbitmq_cluster=~\"$rabbitmq_cluster\"})"
    }
   },
   {
    "name": "rabbitmq_queue",
    "label": "rabbitmq_queue",
    "query": {
     "query": "label_values(rabbitmq_queue_messages{cluster=~\"$cluster\", namespace=~\"$namespace\", vhost=~\"$rabbitmq_vhost\"},queue)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Queue $rabbitmq_queue on vhost $rabbitmq_vhost ($cluster/$namespace/$rabbitmq_cluster)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "rabbitmq_queue"
  },
  {
   "title": "Queue length",
   "type": "timeseries",
   "description": "Total number of messages in the queue, including unacknowledged messages. For best performance, queues should be empty. \n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{vhost=~\"$rabbitmq_vhost\", queue=~\"$rabbitmq_queue\"}  * on(instance, job) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", cluster=~\"$cluster\", namespace=~\"$namespace\"}",
     "legendFormat": "{{queue}} length"
    }
   ]
  },
  {
   "title": "Consumer count",
   "type": "timeseries",
   "description": "The total number of consumers subscribed to the queue.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "rabbitmq_queue_consumers{queue=~\"$rabbitmq_queue\", vhost=~\"$rabbitmq_vhost\"}  * on(instance, job) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", cluster=~\"$cluster\", namespace=~\"$namespace\"}",
     "legendFormat": "{{queue}} consumer count"
    }
   ]
  },
  {
   "title": "Messages ready",
   "type": "timeseries",
   "description": "Total number of ready messages in the queue. \n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{vhost=~\"$rabbitmq_vhost\", queue=~\"$rabbitmq_queue\"}  * on(instance, job) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", cluster=~\"$cluster\", namespace=~\"$namespace\"}",
     "legendFormat": "{{queue}} length"
    }
   ]
  },
  {
   "title": "Messages unacknowledged",
   "type": "timeseries",
   "description": "The count of messages delivered to consumers that are pending acknowledgment before they can be removed from the queue.\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_unacked{queue=~\"$rabbitmq_queue\", vhost=~\"$rabbitmq_vhost\"}  * on(instance, job) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", cluster=~\"$cluster\", namespace=~\"$namespace\"}",
     "legendFormat": "Unacknowledged messages count for {{queue}} ({{vhost}})"
    }
   ]
  },
  {
   "title": "Messages published",
   "type": "timeseries",
   "description": "Total number of published messages in the queue.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_published_total{vhost=~\"$rabbitmq_vhost\", queue=~\"$rabbitmq_queue\"}  * on(instance, job) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", cluster=~\"$cluster\", namespace=~\"$namespace\"}",
     "legendFormat": "{{queue}} length"
    }
   ]
  },
  {
   "title": "Messages delivered",
   "type": "timeseries",
   "description": "Total number of delivered messages in the queue.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_delivered_total{vhost=~\"$rabbitmq_vhost\", queue=~\"$rabbitmq_queue\"}  * on(instance, job) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", cluster=~\"$cluster\", namespace=~\"$namespace\"}",
     "legendFormat": "{{queue}} length"
    }
   ]
  },
  {
   "title": "Acknowledgment and delivery rate",
   "type": "timeseries",
   "description": "- **Acknowledgment rate:** The frequency at which acknowledgments from consumers are received, allowing messages to be removed from the queue.\n- **Auto-ack rate:** Messages removed from the queue without acknowledgment. \n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by (queue, rabbitmq_node) (rate(rabbitmq_channel_messages_acked_total{queue=~\"$rabbitmq_queue\", vhost=~\"$rabbitmq_vhost\"}[$__rate_interval])  * on(instance, job) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", cluster=~\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "Consumed with acknowledgement on {{rabbitmq_node}}"
    },
    {
     "expr": "sum by (queue, rabbitmq_node) (rate(rabbitmq_channel_messages_delivered_total{queue=~\"$rabbitmq_queue\", vhost=~\"$rabbitmq_vhost\"}[$__rate_interval])  * on(instance, job) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "Consumed with auto-ack on {{rabbitmq_node}}"
    }
   ]
  },
  {
   "title": "Incoming message rate",
   "type": "timeseries",
   "description": "Rate of new messages inserted into the queue.\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by (rabbitmq_cluster, vhost, rabbitmq_node) (rate(rabbitmq_queue_messages_published_total{vhost=~\"$rabbitmq_vhost\", queue=~\"$rabbitmq_queue\"}[$__rate_interval])  * on(instance, job) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", cluster=~\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "Published on {{rabbitmq_node}}"
    }
   ]
  },
  {
   "title": "Message polling rates",
   "type": "timeseries",
   "description": "Rate of client applications polling the queue for messages. \n\nThe metrics shown are the following:\n\n- **Queue Polling with Acknowledgment:** In this mode, the queue requires an acknowledgment from the client to confirm message processing before removing the message from the queue.\n- **Queue Polling without Acknowledgment:** Messages are immediately removed from the queue once served, with no need for processing acknowledgment from the client.\n- **Polling on Empty Queue:** This metric tracks the count of poll events when the queue is empty, indicating unnecessary polling activity.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by (queue, rabbitmq_node) (rate(rabbitmq_channel_get_ack_total{queue=~\"$rabbitmq_queue\", vhost=~\"$rabbitmq_vhost\"}[$__rate_interval])  * on(instance, job) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "Consumed with acknowledgement on {{rabbitmq_node}}"
    },
    {
     "expr": "sum by (queue, rabbitmq_node) (rate(rabbitmq_channel_get_total{queue=~\"$rabbitmq_queue\", vhost=~\"$rabbitmq_vhost\"}[$__rate_interval])  * on(instance, job) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "Consumed with auto-ack on {{rabbitmq_node}}"
    },
    {
     "expr": "sum by (queue, rabbitmq_node) (rate(rabbitmq_channel_get_empty_total{queue=~\"$rabbitmq_queue\", vhost=~\"$rabbitmq_vhost\"}[$__rate_interval])  * on(instance, job) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "Basic.get returned empty on {{rabbitmq_node}}"
    }
   ]
  }
 ]
}