{
 "title": "uWSGI Dashboard",
 "description": "Simple Dashboard for uWSGI Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(uwsgi_workers, namespace)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(uwsgi_workers{namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "Worker",
    "query": {
     "query": "label_values(uwsgi_worker_apps, worker_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Worker - Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "uwsgi workers statuses",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "uwsgi_worker_busy{namespace=\"$namespace\", pod=\"$Pod\"}",
     "legendFormat": "Worker {{worker_id}}"
    }
   ]
  },
  {
   "title": "Worker - Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Per-second rate of done requests looking up to 5 minutes back.",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(uwsgi_worker_app_requests_total{pod=\"$Pod\", namespace=\"$namespace\"} [$__rate_interval])",
     "legendFormat": "Worker - {{worker_id}}"
    }
   ]
  },
  {
   "title": "Average Response time per request",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "uwsgi_worker_average_response_time_seconds{pod=\"$Pod\", namespace=\"$namespace\"}",
     "legendFormat": "Worker - {{worker_id}}"
    }
   ]
  },
  {
   "title": "RSS",
   "type": "graph",
   "description": "Physically Resident Memory",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "uwsgi_worker_rss_bytes{pod=\"$Pod\", namespace=\"$namespace\"}",
     "legendFormat": "Worker - {{worker_id}}"
    }
   ]
  },
  {
   "title": "VSZ",
   "type": "graph",
   "description": "Virtual Memory Size",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "uwsgi_worker_vsz_bytes{pod=\"$Pod\", namespace=\"$namespace\"}",
     "legendFormat": "Worker - {{worker_id}}"
    }
   ]
  },
  {
   "title": "Served Data size",
   "type": "graph",
   "description": "Virtual Memory Size",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "uwsgi_worker_transmitted_bytes_total{pod=\"$Pod\", namespace=\"$namespace\"}",
     "legendFormat": "Worker - {{worker_id}}"
    }
   ]
  },
  {
   "title": "Respawn/Exceptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Increase of workers RESPAWNs looking up to 5 minutes back.",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(uwsgi_worker_respawn_count_total{pod=\"$Pod\", namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Worker - {{worker_id}}"
    }
   ]
  },
  {
   "title": "Increase of workers EXCEPTIONS looking up to 5 minutes back.",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(uwsgi_worker_exceptions_total{pod=\"$Pod\", namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "Worker - {{worker_id}}"
    }
   ]
  }
 ]
}