{
 "title": "Volumes GC",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(up{job=\"cluster-manager/cluster-manager-metrics-gc\"}, cluster)"
    }
   },
   {
    "name": "storage_provider",
    "label": "Storage provider",
    "query": {
     "query": "label_values(storage_provider_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Volume without PV",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cluster_manager_gc_volume_without_pv_created_at_timestamp{cluster=\"$cluster\", storage_provider_name=\"$storage_provider\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Volume without PV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "count(cluster_manager_gc_volume_without_pv_created_at_timestamp{cluster=\"$cluster\", storage_provider_name=\"$storage_provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PV without PVC",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "cluster_manager_gc_pv_without_pvc_creation_timestamp{cluster=\"$cluster\", storage_provider_name=\"$storage_provider\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PV without PVC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "targets": [
    {
     "expr": "count(cluster_manager_gc_pv_without_pvc_creation_timestamp{cluster=\"$cluster\", storage_provider_name=\"$storage_provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Volume without node",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "cluster_manager_gc_volume_without_node_created_at_timestamp{cluster=\"$cluster\", storage_provider_name=\"$storage_provider\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Volume without node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 16 },
   "targets": [
    {
     "expr": "count(cluster_manager_gc_volume_without_node_created_at_timestamp{cluster=\"$cluster\", storage_provider_name=\"$storage_provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PVC without PV",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "cluster_manager_gc_pvc_without_pv_creation_timestamp{cluster=\"$cluster\", storage_provider_name=\"$storage_provider\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PVC without PV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 24 },
   "targets": [
    {
     "expr": "count(cluster_manager_gc_pvc_without_pv_creation_timestamp{cluster=\"$cluster\", storage_provider_name=\"$storage_provider\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PV to skip",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "cluster_manager_gc_pv_to_skip_timestamp{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PV without Volume",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "cluster_manager_gc_pv_without_volume",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}